#rm -f linting_formatting_example_blacked.py
#cp linting_formatting_example_original.py linting_formatting_example_blacked.py
#black linting_formatting_example_blacked.py
black --diff linting_formatting_example_original.py
